sudo: true
language: go
go:
  - 1.6
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/Masterminds/glide
  - glide up
  - pwd
  - ls -l
install:
  - ls
  - du -a vendor
script:
  - bash travis.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ghr --username u-root --token $GITHUB_TOKEN --replace --prerelease --debug `git describe --always`  dist/; fi

notifications:
  slack: u-root:S74GnNB8ekAiqNYTjwbEhkQE
